const AppError = require("../utils/appError");
async function signUp(req, res) {
  try {
    let newUser = req.body;
    const pool = req;
  } catch (error) {}
}
